### ISSUE TITLE
Filter lists of events by category

### ISSUE THREAD

**Issue by nfreear** [firemankurt/MyCalendar#18]
Hi,

I'm creating events with categories like "online", "face-to-face", "london" and so on.

I'd like to be able to display a list of just online events, or just events in London, for example:

```
{% component 'ListEvents' category='online' %}
```

And:
```
{% component 'ListEvents' category='london' %}
```

As an interim step, I'd be happy to have the categories exposed in the HTML, so that list-items can just be hidden using CSS, for example:

HTML:
```html
<body class="page-online-events">
...

<ul class="eventList">
    <li class="cat-online" >About the online event ... </li>
    <li class="cat-f2f cat-london" >About the London workshop ... </li>
...
</ul>
```

CSS styles:
```css
.eventList li {
    display: none;
}
.page-online-events .eventList .cat-online {
    display: list-item;
}

// ...
```

I'll submit some patches shortly ...

Thank you!

Nick
